name: Version Control

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Exit early if sender is github-actions[bot]
        if: ${{ github.event.sender.login == 'github-actions[bot]' }}
        run: |
          echo "Exiting early: sender is github-actions[bot]"
          exit 0

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get next version
        id: get_next_version
        run: |
          chmod +x ./scripts/get_next_version.sh
          echo "Getting next version"
          COMMIT_MSG="$(git log -1 --pretty=%B)"
          echo "COMMIT_MSG=$COMMIT_MSG"
          ./scripts/get_next_version.sh "$COMMIT_MSG"
        shell: bash

      - name: Update version
        if: ${{ github.event.sender.login != 'github-actions[bot]' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_VERSION: ${{ steps.get_next_version.outputs.NEXT_VERSION }}
        id: version_update
        run: |
          chmod +x ./scripts/version_bump.sh
          ./scripts/version_bump.sh "$NEXT_VERSION"

      - name: Create Pull Request
        if: ${{ github.event.sender.login != 'github-actions[bot]' }}
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "AUTO: Version bump ${{ steps.get_next_version.outputs.NEXT_VERSION }}"
          title: "AUTO: Version bump ${{ steps.get_next_version.outputs.NEXT_VERSION }}"
          body: "Automated version bump PR"
          branch: "auto/version-bump-${{ steps.get_next_version.outputs.NEXT_VERSION }}"
          base: main
          delete-branch: true

      - name: Tag commit with version
        if: ${{ steps.cpr.outputs.pull-request-number }}
        env:
          NEXT_VERSION: ${{ steps.get_next_version.outputs.NEXT_VERSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin "auto/version-bump-${NEXT_VERSION}"
          git checkout "auto/version-bump-${NEXT_VERSION}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "$NEXT_VERSION"
          git push origin "$NEXT_VERSION"

      - name: Enable Pull Request Auto-merge
        if: ${{ steps.cpr.outputs.pull-request-number }}
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash

      - name: Set success status for bot commits or no src changes
        if: ${{ github.event.sender.login == 'github-actions[bot]' }}
        run: |
          if [ "${{ github.event.sender.login }}" == "github-actions[bot]" ]; then
            echo "No version bump needed - commit was from bot"
          else
            echo "No version bump needed - no changes in src directory"
          fi
          exit 0
